"""Users

Revision ID: 09dd9bc3c44c
Revises: 56383487d9bb
Create Date: 2023-01-16 13:12:13.338328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09dd9bc3c44c"
down_revision = "56383487d9bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String, unique=True, nullable=False),
        sa.Column("password", sa.String, nullable=False),
        sa.Column(
            "date_created", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()")
        ),
        sa.Column(
            "date_updated", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_refresh_token",
        sa.Column("id", sa.Integer),
        sa.Column("user_id", sa.Integer, nullable=False),
        sa.Column("token", sa.String, nullable=False),
        sa.Column(
            "date_created", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()")
        ),
        sa.Column(
            "date_updated", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    pass


def downgrade() -> None:
    op.drop_constraint("user_refresh_token_user_id_fkey", "user_refresh_token")
    op.drop_table("user_refresh_token")
    op.drop_table("users")
    pass
